### ISSUE TITLE
Analize behavior of websocket transport when BFF is restarted

### ISSUE THREAD

**Issue by hugoArregui** [decentraland/comms-v3#42]
- Today we saw a player was still connected after the BFF was restarted in hela
- We saw a weird big player count in dg and hela, probably because we didn't receive disconnects
     - at this point also we got slow consumers

**Comment by hugoArregui** [comment]
```

Sep 12 12:23:05 peer-ec2 explorer-bff[1549]: 2022-09-12T12:23:05.760Z [ERROR] (rpc-server): Error handling remote request#011{
"message":"Module CommsService is not available for port kernel (4051))",
"name":"Error",
"stack":"Error: Module CommsService is not available for port kernel (4051))
    at Object.loadModule (/app/node_modules/@dcl/rpc/dist/server.js:82:19)
    at handleRequestModule (/app/node_modules/@dcl/rpc/dist/server.js:126:37)
    at handleMessage (/app/node_modules/@dcl/rpc/dist/server.js:263:19)
    at /app/node_modules/@dcl/rpc/dist/server.js:299:35
    at /app/node_modules/mitt/dist/mitt.js:1:255
    at Array.map (<anonymous>)
    at Object.emit (/app/node_modules/mitt/dist/mitt.js:1:239)
    at WebSocket.<anonymous> (/app/node_modules/@dcl/rpc/dist/transports/WebSocket.js:54:20)
    at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)"}
```

**Comment by hugoArregui** [comment]
`Subscription not found`
